### ISSUE TITLE
Any other branches than `master` must not increment the Patch level

### ISSUE THREAD

**Issue by siredmar** [elbb/bb-gitversion#15]
Currently any other branches increment the patch level of the version. 
Refering to this discussion https://github.com/elbb/bb-gitversion/pull/14#issuecomment-635120178 the patch level of the generated version must not be incremented. The increment happens as a manual step when a git tag is created.
The current behavior is:

```
master, sha1 -> 0.1.1
|
| \ make branch test: 
|    sha2 -> 0.1.2-1.Branch.test.sha2
|    sha3 -> 0.1.2-2.Branch.test.sha3
| / merge test into master
| manually tag to 0.2.0
```

By fixing this bug the resulting versioning behavior looks like this:

```
master, sha1 -> 0.1.1
|
| \ make branch test: 
|    sha2 -> 0.1.1-1.Branch.test.sha2
|    sha3 -> 0.1.1-2.Branch.test.sha3
| / merge test into master
| manually tag to 0.2.0
```

**Comment by mlilien** [comment]
fixed with #16
