### ISSUE TITLE
Please add `InformationalVersionDockerLabel`

### ISSUE THREAD

**Issue by siredmar** [elbb/bb-gitversion#35]
As of the latest changes coming with 0.8.0 i am missing the explicit usage of `InformationalVersion` as docker image version.
Would you mind adding `InformationalVersionDockerLabel` in the style of `FullSemVerDockerLabel`?

Thanks!

**Comment by mlilien** [comment]
Seems we should fix that more generic and add an option to generate corresponding `DockerLabel` for all `vars`.

**Comment by siredmar** [comment]
If there would be both `<var>` AND `<var>DockerLabel` then yes! This would be perfect!

**Comment by siredmar** [comment]
Any update on this one?

**Comment by mlilien** [comment]
Hi Armin, 

unfortunately not. It's currently not very high prioritized on my todo list.

Regards, Marcel

**Comment by siredmar** [comment]
It seems like the only one missing that contains a '+' character is InformationalVersion (at least for now).
Would you accept a PR that adds the DockerLabel for InformationalVersion only?

**Comment by mlilien** [comment]
yes

**Comment by siredmar** [comment]
closed by #37
