### ISSUE TITLE
Github Action for bb-gitversion

### ISSUE THREAD

**Issue by siredmar** [elbb/bb-gitversion#39]
Is it possible for you to create a github action for bb-gitversion?

**Comment by mlilien** [comment]
Hi Armin, currently it's not planned. What do you want to achieve?

**Comment by siredmar** [comment]
I want to achieve using bb-gitversion in Github actions :)
We currently have some github ci/cd pipelines where it would be nice if we could use bb-gitversion natively.

**Comment by mlilien** [comment]
I'm closing this issue for now. We won't work on it anytime soon.
