### ISSUE TITLE
When and how to create a Release

### ISSUE THREAD

**Issue by siredmar** [elbb/bb-gitversion#6]
@mlilien @FlorianReinhold @JoergZeidler
Currently we don't have any process that defines the workflow of generating new releases.
As gitversion always takes the last set SemVer tag in the repo to create a new version, we should define a process of creating those tags.
My proposal:

Do your changes in a PR containing Changelog modifications.
Merge the PR after review to master
Tag the new master branch e.g. 0.2.1 (if previous was 0.2.0)
(Either locally or) by CI/CD build the release triggered by tag
With this proposal it is possible to generate several versions e.g. 0.2.2. We previously discussed that making a release by tagging is a manual step. Intermediate commit between releases won't create a release, because no new tag was set (unless we define some test-tags or developemt-tags).
So what do you think?

**Comment by mlilien** [comment]
@siredmar @FlorianReinhold @JoergZeidler ImHo we can close this issue. Can we?
Otherwise copy the issue to the main projects repo.

**Comment by FlorianReinhold** [comment]
yes, we can! ;-)
